name: Chrome headless

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          spec: cypress/integration/a11y_spec.js
